/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.mcguaman.sistemaregistro.Presentacion;

import ec.edu.mcguaman.sistemaregistro.Negocio.PersonaServicio;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import modelo.Persona;

/**
 *
 * @author ASUS
 */
public class frm_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form persona_frm
     */
    private PersonaServicio servicio;
    private SimpleDateFormat formato;
    public static DefaultTableModel modelo;
    private List<Persona> listadoPersonas;

    public frm_Usuario() {
        initComponents();
        servicio = new PersonaServicio();
        this.formato = new SimpleDateFormat("dd-MM-yyyy");
        List<Persona> lista = servicio.ObtenerPersona();
        mostrarDatos(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        butt_agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuario = new javax.swing.JTable();
        butt_eliminar = new javax.swing.JButton();
        butt_actualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        txt_fecha = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Sistema Registro");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Correo:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Fecha Nacimiento (dd-mm-yyyy):");

        jLabel6.setText("Cedula:");

        txt_correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        butt_agregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        butt_agregar.setText("Agregar");
        butt_agregar.setBorder(null);
        butt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_agregarActionPerformed(evt);
            }
        });

        tbl_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_usuario);

        butt_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        butt_eliminar.setText("Eliminar");
        butt_eliminar.setBorder(null);
        butt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_eliminarActionPerformed(evt);
            }
        });

        butt_actualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        butt_actualizar.setText("Actualizar");
        butt_actualizar.setBorder(null);
        butt_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_actualizarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("SISTEMA REGISTRO USUARIO");

        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setBorder(null);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        txt_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fechaKeyPressed(evt);
            }
        });

        txt_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });

        txt_apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });

        txt_cedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });

        txt_telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butt_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(txt_nombre)
                            .addComponent(txt_apellido)
                            .addComponent(txt_cedula)
                            .addComponent(txt_telefono)
                            .addComponent(txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txt_fecha))
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butt_agregar)
                            .addComponent(butt_eliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_limpiar)
                            .addComponent(butt_actualizar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarDatos(List<Persona> listaPersona) {
        listadoPersonas = listaPersona;
        modelo = new DefaultTableModel();
        modelo.addColumn("ID"); //0
        modelo.addColumn("Cedula");//1
        modelo.addColumn("Nombre");//2
        modelo.addColumn("Apellido");//3
        modelo.addColumn("Correo");//4
        modelo.addColumn("Fecha Nacimiento");//5
        modelo.addColumn("Edad");//6
        modelo.addColumn("Telefono");//7

        for (Persona pers : listaPersona) {
            Object[] fila = {pers.getId(), pers.getCedula(), pers.getNombre(), pers.getApellido(), pers.getCorreo(), pers.getFecha_nacimiento(), pers.getEdad(), pers.getTelefono()};
            modelo.addRow(fila);
        }
        tbl_usuario.setModel(modelo);
    }

    private void llenarFormularioDesdeTabla() {
        int filaSeleccionada = tbl_usuario.getSelectedRow();

        if (filaSeleccionada >= 0) {
            // Obtenemos el objeto Persona desde la lista
            Persona personaSeleccionada = listadoPersonas.get(filaSeleccionada);

            txt_nombre.setText(personaSeleccionada.getNombre());
            txt_apellido.setText(personaSeleccionada.getApellido());
            txt_cedula.setText(personaSeleccionada.getCedula());
            txt_correo.setText(personaSeleccionada.getCorreo());
            txt_telefono.setText(personaSeleccionada.getTelefono());

            // Convertir LocalDate a String con formato dd-MM-yyyy
            LocalDate fechaNacimiento = personaSeleccionada.getFecha_nacimiento();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            txt_fecha.setText(fechaNacimiento.format(formatter));
        }
    }

    // Se emplea este metodo para poder limpiar el formulario
    private void LimpiarFormulario() {
        txt_apellido.setText("");
        txt_cedula.setText("");
        txt_correo.setText("");
        txt_nombre.setText("");
        txt_telefono.setText("");
        txt_fecha.setText("");
    }

    private void butt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_agregarActionPerformed
        // Si el formulario esta lleno proceder a enviarlo a la capa de negocio
        if (ValidarFormulario()) {
            String nombre = txt_nombre.getText();
            String apellido = txt_apellido.getText();
            String cedula = txt_cedula.getText();
            String correo = txt_correo.getText();
            String telefono = txt_telefono.getText();

            // 26-09-1994
            String fecha = txt_fecha.getText();
            String[] fechaSeparada = fecha.split("-");

            int dia = Integer.parseInt(fechaSeparada[0]);
            int mes = Integer.parseInt(fechaSeparada[1]);
            int anio = Integer.parseInt(fechaSeparada[2]);
            LocalDate fechaNacimiento = LocalDate.of(anio, mes, dia);

            //String nombre, String apellido, String correo, String telefono, LocalDate fecha_nacimiento, String cedula
            Persona nuevaPersona = new Persona(nombre, apellido, correo,
                    telefono, fechaNacimiento, cedula);

            // [0] ya existe la persomna  [1] registro de persona exitoso
            // [2] Error interno [3] la persona es menor de edad
            int registro = servicio.AgregarNuevsPersona(nuevaPersona);

            switch (registro) {
                case 0:
                    JOptionPane.showMessageDialog(null,
                            "Ya existe la persona con ese número de cédula.",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE);
                    break;

                case 1:
                    JOptionPane.showMessageDialog(null,
                            "Registro exitoso.",
                            "Información",
                            JOptionPane.INFORMATION_MESSAGE);
                    // Se procede a actualizar la tabla de registro y limpiar el formulario
                    List<Persona> lista = servicio.ObtenerPersona();
                    mostrarDatos(lista);
                    LimpiarFormulario();
                    break;

                case 2:
                    JOptionPane.showMessageDialog(null,
                            "Error interno, intentelo más tarde.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    break;

                case 3:
                    JOptionPane.showMessageDialog(null,
                            "El sistema solo permite registrar a mayores de edad.",
                            "Advertencia",
                            JOptionPane.QUESTION_MESSAGE);
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Debe completar todos los campos obligatorios.",
                    "Advertencia",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_butt_agregarActionPerformed

    private void butt_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_actualizarActionPerformed
        // Se obtiene el id seleccionado de la tabla
        int filaSeleccionada = tbl_usuario.getSelectedRow();
        // Se valdia que la fila seleccionada sea superior a cero 
        if (filaSeleccionada >= 0) {

            // Si el formulario esta lleno proceder a enviarlo a la capa de negocio
            if (ValidarFormulario()) {
                String nombre = txt_nombre.getText();
                String apellido = txt_apellido.getText();
                String cedula = txt_cedula.getText();
                String correo = txt_correo.getText();
                String telefono = txt_telefono.getText();

                // 26-09-1994
                String fecha = txt_fecha.getText();
                String[] fechaSeparada = fecha.split("-");

                int dia = Integer.parseInt(fechaSeparada[0]);
                int mes = Integer.parseInt(fechaSeparada[1]);
                int anio = Integer.parseInt(fechaSeparada[2]);
                LocalDate fechaNacimiento = LocalDate.of(anio, mes, dia);

                //String nombre, String apellido, String correo, String telefono, LocalDate fecha_nacimiento, String cedula
                Persona actualizarPersona = new Persona(nombre, apellido, correo,
                        telefono, fechaNacimiento, cedula);

                int idPersona = listadoPersonas.get(filaSeleccionada).getId();

                boolean actualizado = servicio.ActualizarPersona(idPersona, actualizarPersona);

                if (actualizado) {
                    JOptionPane.showMessageDialog(null,
                            "Registro actualizado.",
                            "Información",
                            JOptionPane.INFORMATION_MESSAGE);
                    List<Persona> lista = servicio.ObtenerPersona();
                    mostrarDatos(lista);
                    LimpiarFormulario();
                } else {
                    JOptionPane.showMessageDialog(null,
                            "No se pudo actualizar el registro.",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_butt_actualizarActionPerformed

    private void butt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_eliminarActionPerformed
        // Se obtiene el id seleccionado de la tabla
        int filaSeleccionada = tbl_usuario.getSelectedRow();

        // Se valdia que la fila seleccionada sea superior a cero 
        if (filaSeleccionada >= 0) {
            // Confirmar antes de eliminar
            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro de eliminar esta persona?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                int idPersona = listadoPersonas.get(filaSeleccionada).getId();
                System.out.println("El id" + idPersona);

                boolean eliminado = servicio.EliminarPersonaPorId(idPersona);

                if (eliminado) {
                    JOptionPane.showMessageDialog(null, "Persona eliminada correctamente.");
                    List<Persona> listaPersona = servicio.ObtenerPersona();
                    mostrarDatos(listaPersona);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar la persona.");
                }
            }
        }
    }//GEN-LAST:event_butt_eliminarActionPerformed

    public void desactivarAgregar(boolean activo) {
        if (activo) {
            butt_agregar.setEnabled(false);
        } else {
            butt_agregar.setEnabled(true);
        }
    }

    private void tbl_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioMouseClicked
        llenarFormularioDesdeTabla();
    }//GEN-LAST:event_tbl_usuarioMouseClicked

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        LimpiarFormulario();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            // Si es 'Delete' o 'Backspace', no hacemos nada y permitimos borrar
            return;
        }

        // Solo validamos si no es una tecla de borrar
        char caracter = evt.getKeyChar();

        // Permitir solo números (0-9) y la raya '-'
        if ((caracter < '0' || caracter > '9') && caracter != '-') {
            evt.consume();  // Si no es un número ni una raya, se descarta el evento

            // Mostrar un mensaje de error si el carácter no es válido
            JOptionPane.showMessageDialog(null, "Error: Solo se permiten números y el carácter '-'.", "Carácter no válido", JOptionPane.ERROR_MESSAGE);
        }

        // Limitar la longitud de la cadena de texto a 10 caracteres (dd-mm-yyyy)
        if (txt_fecha.getText().length() >= 10) {
            evt.consume();  // Si se superan los 10 caracteres, se descarta el evento

            // Mostrar un mensaje de error si se supera el límite de caracteres
            JOptionPane.showMessageDialog(null, "Error: La fecha debe tener exactamente 10 caracteres.", "Límite de caracteres excedido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_fechaKeyPressed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        ValidarCaracteres(evt);
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        ValidarCaracteres(evt);
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
        char c = evt.getKeyChar();

        // 1) Permitir controles (Backspace, Delete…)
        if (Character.isISOControl(c)) {
            return;
        }
        // 2) Sólo dígitos
        if (!Character.isDigit(c)) {
            evt.consume();
            JOptionPane.showMessageDialog(
                    null,
                    "Error: Sólo se permiten dígitos en la cédula.",
                    "Carácter no válido",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        // 3) Longitud máxima 10
        if (txt_cedula.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(
                    null,
                    "Error: La cédula debe tener como máximo 10 dígitos.",
                    "Límite excedido",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        char c = evt.getKeyChar();

        if (Character.isISOControl(c)) {
            return;
        }
        if (!Character.isDigit(c)) {
            evt.consume();
            JOptionPane.showMessageDialog(
                    null,
                    "Error: Sólo se permiten dígitos en el teléfono.",
                    "Carácter no válido",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (txt_telefono.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(
                    null,
                    "Error: El teléfono debe tener como máximo 10 dígitos.",
                    "Límite excedido",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    // Método para validar Nombre/Apellido: letras (incluye tildes/ñ) y espacios
    private void ValidarCaracteres(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();

        // Permitir controles (Backspace, Delete, flechas…)
        if (Character.isISOControl(c)) {
            return;
        }
        // Solo letras y espacios (incluye letras con tildes, ñ, Ñ)
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
            JOptionPane.showMessageDialog(
                    null,
                    "Error: Sólo se permiten letras, tildes y espacios en este campo.",
                    "Carácter no válido",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    public boolean ValidarFormulario() {
        Border bordeRojo = BorderFactory.createLineBorder(Color.RED, 2);
        Border bordeNegro = BorderFactory.createLineBorder(Color.BLACK, 2);

        txt_cedula.setBorder(txt_cedula.getText().trim().isEmpty() ? bordeRojo : bordeNegro);
        txt_correo.setBorder(txt_correo.getText().trim().isEmpty() ? bordeRojo : bordeNegro);
        txt_nombre.setBorder(txt_nombre.getText().trim().isEmpty() ? bordeRojo : bordeNegro);
        txt_apellido.setBorder(txt_nombre.getText().trim().isEmpty() ? bordeRojo : bordeNegro);
        txt_telefono.setBorder(txt_telefono.getText().trim().isEmpty() ? bordeRojo : bordeNegro);
        txt_fecha.setBorder(txt_fecha.getText().trim().isEmpty() ? bordeRojo : bordeNegro);

        return !(txt_cedula.getText().trim().isEmpty()
                || txt_correo.getText().trim().isEmpty()
                || txt_nombre.getText().trim().isEmpty()
                || txt_telefono.getText().trim().isEmpty()
                || txt_fecha.getText().trim().isEmpty());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton butt_actualizar;
    private javax.swing.JButton butt_agregar;
    private javax.swing.JButton butt_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTable tbl_usuario;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
