/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.mcguaman.sistemaregistro.Presentacion;

import ec.edu.mcguaman.sistemaregistro.Negocio.FacturaServicio;
import ec.edu.mcguaman.sistemaregistro.Negocio.PersonaServicio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetalleFactura;
import modelo.Factura;
import modelo.Persona;
import modelo.Producto;

/**
 *
 * @author ASUS
 */
public class frm_SistemaFactura extends javax.swing.JInternalFrame {

    private List<DetalleFactura> detallesFactura = new ArrayList();
    private Producto productoEncontrado;
    private Persona personaEncontrada;

    public static DefaultTableModel modelo;

    // Crea una instancia de la clase FacturaServicio
    private FacturaServicio servicio;

    private PersonaServicio servicioPersona;

    /**
     * Creates new form SistemaFactura
     */
    public frm_SistemaFactura() {
        initComponents();
        servicio = new FacturaServicio();
        servicioPersona = new PersonaServicio();

        // Deshabilitar los botones y campos de texto al inicio
        this.btn_BuscarIdProducto.setEnabled(false);
        this.btn_agregarDetalleFactura.setEnabled(false);
        this.btn_EliminarProducto.setEnabled(false);
        this.btn_LimpiarProuctos.setEnabled(false);

        this.txt_IdUser.setEnabled(true);

        this.btn_buscarPersona.setEnabled(true);

        // Inicializar las tablas de productos y factura
        DefaultTableModel productoModel = new DefaultTableModel();
        productoModel.addColumn("ID Detalle");
        productoModel.addColumn("ID Producto");
        productoModel.addColumn("Producto");
        productoModel.addColumn("Cantidad");
        productoModel.addColumn("Precio Unitario");
        productoModel.addColumn("Total");
        tbl_productos.setModel(productoModel);

        DefaultTableModel facturaModel = new DefaultTableModel();
        facturaModel.addColumn("ID Factura");
        facturaModel.addColumn("Nombre Cliente");
        facturaModel.addColumn("Subtotal");
        facturaModel.addColumn("IVA 12%");
        facturaModel.addColumn("Total");
        tbl_detallesFactura.setModel(facturaModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detallesFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_IdUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_IdProduct = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        btn_agregarDetalleFactura = new javax.swing.JButton();
        btn_EliminarProducto = new javax.swing.JButton();
        btn_BuscarIdProducto = new javax.swing.JButton();
        btn_buscarPersona = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cedC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nombreProducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_LimpiarProuctos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_codProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_iva = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Factura");

        tbl_detallesFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_detallesFactura);

        jLabel1.setText("Inserte dato númerico para buscar cliente por ID:");

        txt_IdUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdUserKeyTyped(evt);
            }
        });

        jLabel2.setText("Inserte dato númerico para buscar producto por ID:");

        txt_IdProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdProductKeyTyped(evt);
            }
        });

        jLabel3.setText("Ingrese la Cantidad:");

        jLabel4.setText("Precio:");

        txt_precio.setEditable(false);

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_productos);

        btn_agregarDetalleFactura.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btn_agregarDetalleFactura.setText("AGREGAR PRODUCTO");
        btn_agregarDetalleFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarDetalleFacturaActionPerformed(evt);
            }
        });

        btn_EliminarProducto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btn_EliminarProducto.setText("ELIMINAR PRODUCTO");
        btn_EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarProductoActionPerformed(evt);
            }
        });

        btn_BuscarIdProducto.setText("BUSCAR PRODUCTO");
        btn_BuscarIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarIdProductoActionPerformed(evt);
            }
        });

        btn_buscarPersona.setText("BUSCAR PERSONA");
        btn_buscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarPersonaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre Cliente:");

        txt_nombre.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel6.setText("Detalles de los Productos");

        jLabel7.setText("Cédula Cliente:");

        txt_cedC.setEditable(false);

        jLabel8.setText("Nombre del Producto:");

        txt_nombreProducto.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel10.setText("Detalles de la Factura");

        btn_LimpiarProuctos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btn_LimpiarProuctos.setText("LIMPIAR");
        btn_LimpiarProuctos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarProuctosActionPerformed(evt);
            }
        });

        jLabel9.setText("Código del Producto:");

        txt_codProducto.setEditable(false);

        jLabel11.setText("Subtotal:");

        jLabel12.setText("IVA 12%:  ");

        jLabel13.setText("Total:");

        jLabel14.setText("Apellido Cliente:");

        txt_apellido.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_IdProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_IdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_buscarPersona))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_apellido))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_agregarDetalleFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_EliminarProducto))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txt_nombreProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn_BuscarIdProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(121, 121, 121))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(btn_LimpiarProuctos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_iva)
                                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(txt_cedC, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_cedC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_IdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_BuscarIdProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregarDetalleFactura)
                            .addComponent(btn_EliminarProducto)
                            .addComponent(btn_LimpiarProuctos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(16, 16, 16)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cargarDatosFactura() {
        // Recuperamos la factura por su ID (debes usar el ID que corresponde)
        Factura factura = servicio.getFacturaById(1);  // O el ID correspondiente según el contexto

        if (factura != null) {
            // Limpiamos la tabla de factura antes de agregar nuevos datos
            DefaultTableModel model = (DefaultTableModel) tbl_detallesFactura.getModel();
            model.setRowCount(0);  // Limpiamos las filas existentes

            // Recorremos los detalles de la factura y agregamos las filas
            for (DetalleFactura detalle : factura.getDetalles()) {
                // Aquí obtenemos los datos del detalle y de la factura
                Object[] row = {
                    factura.getId(), // ID de la factura
                    factura.getPersona().getId(), // ID del cliente
                    factura.getPersona().getCedula(), // Cédula del cliente
                    factura.getPersona().getNombre(), // Nombre del cliente
                    factura.getPersona().getApellido(), // Apellido del cliente
                    factura.getMontoTotal() // Monto Total de la factura (asumido ya calculado)
                };

                // Agregamos la fila a la tabla
                model.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Factura no encontrada.");
        }
    }


    private void btn_buscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarPersonaActionPerformed
        BuscarPersona();
    }//GEN-LAST:event_btn_buscarPersonaActionPerformed

    private void btn_BuscarIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarIdProductoActionPerformed
        BuscarProducto();
    }//GEN-LAST:event_btn_BuscarIdProductoActionPerformed

    private void btn_agregarDetalleFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarDetalleFacturaActionPerformed
        AgregarDetalleFactura();
        LimpiarFormulario();
    }//GEN-LAST:event_btn_agregarDetalleFacturaActionPerformed


    private void txt_IdUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdUserKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Permitir solo dígitos (0-9)
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_IdUserKeyTyped

    private void txt_IdProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdProductKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Permitir solo dígitos (0-9)
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_IdProductKeyTyped

    private void btn_EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarProductoActionPerformed
        EliminarProducto();
    }//GEN-LAST:event_btn_EliminarProductoActionPerformed

    private void btn_LimpiarProuctosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarProuctosActionPerformed
        LimpiarFormulario();
    }//GEN-LAST:event_btn_LimpiarProuctosActionPerformed

    private void LimpiarFormulario() {
        txt_IdProduct.setText("");
        txt_nombreProducto.setText("");
        txt_codProducto.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");
    }

    private void BuscarPersona() {
        int id = Integer.parseInt(this.txt_IdUser.getText());  // Obtener el ID desde el JTextField
        this.personaEncontrada = this.servicioPersona.BuscarPersonaPorId(id);  // Llamamos al servicio

        if (this.personaEncontrada != null) {

// Si encontramos la persona, mostramos los datos
            this.txt_nombre.setText(this.personaEncontrada.getNombre());
            this.txt_cedC.setText(String.valueOf(this.personaEncontrada.getCedula()));
            this.txt_apellido.setText(this.personaEncontrada.getApellido());

// Hacemos que los campos de texto sean solo de lectura
            TextosNoEditables();

// Habilitar la búsqueda de productos
            this.btn_BuscarIdProducto.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
        }
    }

    private void BuscarProducto() {
        String idProductoStr = this.txt_IdProduct.getText();  // Obtener el ID del producto desde el JTextField
        int idProducto = Integer.parseInt(idProductoStr);  // Convertir el ID a un número entero

        // Llamar al servicio para buscar el producto por su ID
        this.productoEncontrado = this.servicio.BuscarProductoPorId(idProducto);

        if (this.productoEncontrado != null) {

// Si se encuentra el producto, mostramos los datos en los campos correspondientes
            this.txt_precio.setText(String.valueOf(this.productoEncontrado.getPrecio()));
            this.txt_nombreProducto.setText(this.productoEncontrado.getNombre());
            this.txt_codProducto.setText(this.productoEncontrado.getCodigo());

// Habilitar el botón de agregar producto a la factura
            this.btn_agregarDetalleFactura.setEnabled(true);
            this.btn_EliminarProducto.setEnabled(true);
            this.btn_LimpiarProuctos.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
        }
    }

    private void AgregarDetalleFactura() {
        int cantidad = Integer.parseInt(this.txt_cantidad.getText());

        if (this.productoEncontrado != null) {
            float precioUnitario = this.productoEncontrado.getPrecio().floatValue();
            float total = cantidad * precioUnitario;

            DefaultTableModel model = (DefaultTableModel) tbl_productos.getModel();
            Object[] row = {tbl_productos.getRowCount() + 1, this.productoEncontrado.getId(), this.productoEncontrado.getNombre(), cantidad,
                precioUnitario, total};
            model.addRow(row);
            actualizarMontoFactura();
        }
    }

    private void actualizarMontoFactura() {
        float subtotal = 0;
        // Sumar los totales de los productos en la tabla de productos
        DefaultTableModel model = (DefaultTableModel) tbl_productos.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            float totalProducto = (float) model.getValueAt(i, 5);  // El total de cada producto está en la columna 5
            subtotal += totalProducto;  // Sumar el total del producto al subtotal
        }

        // Calcular el IVA (12% del subtotal)
        float iva = subtotal * 0.12f;  // 12% de IVA

        // Calcular el total (subtotal + IVA)
        float total = subtotal + iva;

        // Actualizar los cuadros de texto para mostrar los valores
        txt_subtotal.setText(String.format("%.2f", subtotal));  // Subtotal
        txt_iva.setText(String.format("%.2f", iva));            // IVA
        txt_total.setText(String.format("%.2f", total));        // Total

        // Ahora también se actualiza la tabla de la factura
        DefaultTableModel facturaModel = (DefaultTableModel) tbl_detallesFactura.getModel();
        facturaModel.setRowCount(0);  // Limpiar la tabla de factura

        // Agregar la fila con la información actualizada (por ejemplo, con el total calculado)
        Object[] filaFactura = {
            this.personaEncontrada.getId(), // ID Cliente
            this.personaEncontrada.getNombre(), // Nombre Cliente
            subtotal, // Subtotal
            iva, // IVA
            total // Total
        };
        facturaModel.addRow(filaFactura);  // Agregar la fila a la tabla de la factura
    }

    private void EliminarProducto() {
        int selectedRow = tbl_productos.getSelectedRow();  // Obtener la fila seleccionada de la tabla

        if (selectedRow != -1) {
            // Obtener el ID del detalle de la factura (por ejemplo, en la columna 0 se puede guardar el ID de detalle)
            int idDetalle = (int) tbl_productos.getValueAt(selectedRow, 0);  // Columna 0 almacena el ID de detalle

            // Eliminar la fila de la tabla
            DefaultTableModel model = (DefaultTableModel) tbl_productos.getModel();
            model.removeRow(selectedRow);

            // Aquí puedes eliminar el detalle de la factura de la lista `detallesFactura`
            for (DetalleFactura detalle : detallesFactura) {
                if (detalle.getId() == idDetalle) {
                    detallesFactura.remove(detalle);  // Eliminar el detalle de la lista de detalles de la factura
                    break;  // Salir del bucle una vez encontrado el detalle
                }
            }

            // Actualizar el monto total de la factura
            actualizarMontoFactura();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un producto para eliminar.");
        }
    }

    public void TextosNoEditables() {
        this.txt_nombre.setEditable(false);
        this.txt_apellido.setEditable(false);
        this.txt_cedC.setEditable(false);
        this.txt_precio.setEditable(false);
        this.txt_codProducto.setEditable(false);
        this.txt_nombreProducto.setEditable(false);

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarIdProducto;
    private javax.swing.JButton btn_EliminarProducto;
    private javax.swing.JButton btn_LimpiarProuctos;
    private javax.swing.JButton btn_agregarDetalleFactura;
    private javax.swing.JButton btn_buscarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_detallesFactura;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTextField txt_IdProduct;
    private javax.swing.JTextField txt_IdUser;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cedC;
    private javax.swing.JTextField txt_codProducto;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreProducto;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
